version: '2.4'
services:
  web:
    container_name: 'nginx-nepcom-reloaded'
    build: ./build/nginx
    ports:
      - '8880:80'
      - '8443:443'
    volumes:
      - .:/app
  php-fpm:
    container_name: 'php-nepcom-reloaded'
    build: ./build/php
    ports:
      - '9000'
    volumes:
      - .:/app
  mysql:
    container_name: 'mysql-nepcom-reloaded'
    image: mysql:5.7
    ports:
      - "39060:3306"
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'api-user'
        MYSQL_PASSWORD: 'temporal'
        MYSQL_ROOT_PASSWORD: 'temporal'
    volumes:
        - ./data/db:/var/lib/mysql
